server:
  port: 8091
#端口号
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.0.45:1521:orcl
    username: dftg
    password: dftg
  mvc:
    view:
      prefix: /templates/
      suffix: .html
    static-path-pattern: /**
  http:
    encoding:
      charset: UTF-8

mybatis-plus:
  type-aliases-package: com.amac.pojo
  mapper-locations: classpath:/mybatis/mappers/*.xml

  configuration:
    map-underscore-to-camel-case: true