server:
  port: 8091

spring:
  datasource:
    #引入druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: scott
    password: scott

mybatis-plus:
  #identity: ORCAL
  type-aliases-package: com.demo.pojo
  mapper-locations: classpath:/mybatis/mappers/*.xml

  configuration:
    map-underscore-to-camel-case: true